app:
  name: expense-monitor-app
  version:
    v1: v1

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource: 
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    
telegram:
  bot:
    username: ${TELEGRAM_BOT_UN}
    token: ${TELEGRAM_BOT_TOKEN}